package org.lumenvision.photoncompat;

import edu.wpi.first.wpilibj.DriverStation;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Compares this jar's own built-in version against the coprocessor's own {@code .version} NT4
 * topic (NetworkTablesSink.cpp - ROADMAP.md Phase E1), warning on the driver station when they
 * differ - the same mismatch-detection photonlib's own PhotonCamera already does against
 * PhotonVision's backend version, catching "robot code was built against a newer/older
 * photoncompat than what's actually deployed on the coprocessor" before it causes a confusing
 * silent behavior difference instead.
 */
final class LumenVersionCheck {
    private static final String JAR_VERSION = loadJarVersion();

    private LumenVersionCheck() {}

    private static String loadJarVersion() {
        // photoncompat-version.properties is generated by build.gradle's processResources
        // (expand()) from the template of the same name under src/main/resources - the real,
        // built file on the classpath has the actual `version` substituted in, never the literal
        // "${version}" the template contains.
        try (InputStream in = LumenVersionCheck.class.getResourceAsStream("/photoncompat-version.properties")) {
            if (in == null) return "unknown";
            Properties props = new Properties();
            props.load(in);
            return props.getProperty("version", "unknown");
        } catch (IOException e) {
            return "unknown";
        }
    }

    /**
     * @param coprocessorVersion the coprocessor's own {@code .version} topic value - an empty
     *     string (NT4's default-value sentinel for "no value received yet", see
     *     {@link LumenCamera}'s own subscriber setup) means "not connected/synced yet", not a
     *     real mismatch, and is silently ignored rather than reported as one.
     */
    static void warnOnMismatch(String coprocessorVersion) {
        if (coprocessorVersion == null || coprocessorVersion.isEmpty()) return;
        if (coprocessorVersion.equals(JAR_VERSION)) return;
        DriverStation.reportWarning(
                "LumenVision: photoncompat-java version (" + JAR_VERSION
                        + ") does not match the coprocessor's own reported version ("
                        + coprocessorVersion + ") - update one to match the other.",
                false);
    }
}
