#version 450
layout(local_size_x=16, local_size_y=16) in;

layout(binding=0, r8) readonly uniform image2D imgGray;
layout(binding=1, r8) writeonly uniform image2D imgBin;

void main() {
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    // Simple global threshold for demo
    float g = imageLoad(imgGray, uv).r;
    float t = 0.5; // fixed threshold
    float b = g > t ? 1.0 : 0.0;
    imageStore(imgBin, uv, vec4(b,0,0,1));
}