//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ApriltagDetectionPipeline : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ApriltagDetectionPipeline(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ApriltagDetectionPipeline obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ApriltagDetectionPipeline obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ApriltagDetectionPipeline() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FRCVCorePINVOKE.delete_ApriltagDetectionPipeline(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ApriltagDetectionPipeline(IFrameSource frameSource, SWIGTYPE_p_ISinkT_ApriltagDetection_t sink, Logger logger) : this(FRCVCorePINVOKE.new_ApriltagDetectionPipeline(IFrameSource.getCPtr(frameSource), SWIGTYPE_p_ISinkT_ApriltagDetection_t.getCPtr(sink), Logger.getCPtr(logger)), true) {
  }

  public VectorApriltagDetection getResults() {
    global::System.IntPtr cPtr = FRCVCorePINVOKE.ApriltagDetectionPipeline_getResults(swigCPtr);
    VectorApriltagDetection ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorApriltagDetection(cPtr, false);
    return ret;
  }

}
