//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class FRCVCore {
  public static VectorCameraFrameSource enumerateCameras() {
    VectorCameraFrameSource ret = new VectorCameraFrameSource(FRCVCorePINVOKE.enumerateCameras(), true);
    return ret;
  }

}
