//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorVideoFileFrameSource : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<VideoFileFrameSource>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorVideoFileFrameSource(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorVideoFileFrameSource obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorVideoFileFrameSource obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorVideoFileFrameSource() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FRCVCorePINVOKE.delete_VectorVideoFileFrameSource(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorVideoFileFrameSource(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VideoFileFrameSource element in c) {
      this.Add(element);
    }
  }

  public VectorVideoFileFrameSource(global::System.Collections.Generic.IEnumerable<VideoFileFrameSource> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VideoFileFrameSource element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public VideoFileFrameSource this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(VideoFileFrameSource[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(VideoFileFrameSource[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, VideoFileFrameSource[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public VideoFileFrameSource[] ToArray() {
    VideoFileFrameSource[] array = new VideoFileFrameSource[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<VideoFileFrameSource> global::System.Collections.Generic.IEnumerable<VideoFileFrameSource>.GetEnumerator() {
    return new VectorVideoFileFrameSourceEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorVideoFileFrameSourceEnumerator(this);
  }

  public VectorVideoFileFrameSourceEnumerator GetEnumerator() {
    return new VectorVideoFileFrameSourceEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorVideoFileFrameSourceEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<VideoFileFrameSource>
  {
    private VectorVideoFileFrameSource collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorVideoFileFrameSourceEnumerator(VectorVideoFileFrameSource collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public VideoFileFrameSource Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (VideoFileFrameSource)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorVideoFileFrameSource() : this(FRCVCorePINVOKE.new_VectorVideoFileFrameSource__SWIG_0(), true) {
  }

  public VectorVideoFileFrameSource(VectorVideoFileFrameSource other) : this(FRCVCorePINVOKE.new_VectorVideoFileFrameSource__SWIG_1(VectorVideoFileFrameSource.getCPtr(other)), true) {
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_Clear(swigCPtr);
  }

  public void Add(VideoFileFrameSource x) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_Add(swigCPtr, VideoFileFrameSource.getCPtr(x));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = FRCVCorePINVOKE.VectorVideoFileFrameSource_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = FRCVCorePINVOKE.VectorVideoFileFrameSource_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = FRCVCorePINVOKE.VectorVideoFileFrameSource_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_reserve(swigCPtr, n);
  }

  public VectorVideoFileFrameSource(int capacity) : this(FRCVCorePINVOKE.new_VectorVideoFileFrameSource__SWIG_2(capacity), true) {
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private VideoFileFrameSource getitemcopy(int index) {
    VideoFileFrameSource ret = new VideoFileFrameSource(FRCVCorePINVOKE.VectorVideoFileFrameSource_getitemcopy(swigCPtr, index), true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private VideoFileFrameSource getitem(int index) {
    VideoFileFrameSource ret = new VideoFileFrameSource(FRCVCorePINVOKE.VectorVideoFileFrameSource_getitem(swigCPtr, index), false);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, VideoFileFrameSource val) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_setitem(swigCPtr, index, VideoFileFrameSource.getCPtr(val));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorVideoFileFrameSource values) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_AddRange(swigCPtr, VectorVideoFileFrameSource.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorVideoFileFrameSource GetRange(int index, int count) {
    global::System.IntPtr cPtr = FRCVCorePINVOKE.VectorVideoFileFrameSource_GetRange(swigCPtr, index, count);
    VectorVideoFileFrameSource ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVideoFileFrameSource(cPtr, true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, VideoFileFrameSource x) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_Insert(swigCPtr, index, VideoFileFrameSource.getCPtr(x));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorVideoFileFrameSource values) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_InsertRange(swigCPtr, index, VectorVideoFileFrameSource.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_RemoveAt(swigCPtr, index);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_RemoveRange(swigCPtr, index, count);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorVideoFileFrameSource Repeat(VideoFileFrameSource value, int count) {
    global::System.IntPtr cPtr = FRCVCorePINVOKE.VectorVideoFileFrameSource_Repeat(VideoFileFrameSource.getCPtr(value), count);
    VectorVideoFileFrameSource ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVideoFileFrameSource(cPtr, true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_Reverse__SWIG_1(swigCPtr, index, count);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorVideoFileFrameSource values) {
    FRCVCorePINVOKE.VectorVideoFileFrameSource_SetRange(swigCPtr, index, VectorVideoFileFrameSource.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

}
