//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorRknnSink : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<RknnSink>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorRknnSink(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorRknnSink obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorRknnSink obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorRknnSink() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FRCVCorePINVOKE.delete_VectorRknnSink(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorRknnSink(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (RknnSink element in c) {
      this.Add(element);
    }
  }

  public VectorRknnSink(global::System.Collections.Generic.IEnumerable<RknnSink> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (RknnSink element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public RknnSink this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(RknnSink[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(RknnSink[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, RknnSink[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public RknnSink[] ToArray() {
    RknnSink[] array = new RknnSink[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<RknnSink> global::System.Collections.Generic.IEnumerable<RknnSink>.GetEnumerator() {
    return new VectorRknnSinkEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorRknnSinkEnumerator(this);
  }

  public VectorRknnSinkEnumerator GetEnumerator() {
    return new VectorRknnSinkEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorRknnSinkEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<RknnSink>
  {
    private VectorRknnSink collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorRknnSinkEnumerator(VectorRknnSink collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public RknnSink Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (RknnSink)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorRknnSink() : this(FRCVCorePINVOKE.new_VectorRknnSink__SWIG_0(), true) {
  }

  public VectorRknnSink(VectorRknnSink other) : this(FRCVCorePINVOKE.new_VectorRknnSink__SWIG_1(VectorRknnSink.getCPtr(other)), true) {
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    FRCVCorePINVOKE.VectorRknnSink_Clear(swigCPtr);
  }

  public void Add(RknnSink x) {
    FRCVCorePINVOKE.VectorRknnSink_Add(swigCPtr, RknnSink.getCPtr(x));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = FRCVCorePINVOKE.VectorRknnSink_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = FRCVCorePINVOKE.VectorRknnSink_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = FRCVCorePINVOKE.VectorRknnSink_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    FRCVCorePINVOKE.VectorRknnSink_reserve(swigCPtr, n);
  }

  public VectorRknnSink(int capacity) : this(FRCVCorePINVOKE.new_VectorRknnSink__SWIG_2(capacity), true) {
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private RknnSink getitemcopy(int index) {
    RknnSink ret = new RknnSink(FRCVCorePINVOKE.VectorRknnSink_getitemcopy(swigCPtr, index), true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private RknnSink getitem(int index) {
    RknnSink ret = new RknnSink(FRCVCorePINVOKE.VectorRknnSink_getitem(swigCPtr, index), false);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, RknnSink val) {
    FRCVCorePINVOKE.VectorRknnSink_setitem(swigCPtr, index, RknnSink.getCPtr(val));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorRknnSink values) {
    FRCVCorePINVOKE.VectorRknnSink_AddRange(swigCPtr, VectorRknnSink.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorRknnSink GetRange(int index, int count) {
    global::System.IntPtr cPtr = FRCVCorePINVOKE.VectorRknnSink_GetRange(swigCPtr, index, count);
    VectorRknnSink ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorRknnSink(cPtr, true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, RknnSink x) {
    FRCVCorePINVOKE.VectorRknnSink_Insert(swigCPtr, index, RknnSink.getCPtr(x));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorRknnSink values) {
    FRCVCorePINVOKE.VectorRknnSink_InsertRange(swigCPtr, index, VectorRknnSink.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    FRCVCorePINVOKE.VectorRknnSink_RemoveAt(swigCPtr, index);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    FRCVCorePINVOKE.VectorRknnSink_RemoveRange(swigCPtr, index, count);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorRknnSink Repeat(RknnSink value, int count) {
    global::System.IntPtr cPtr = FRCVCorePINVOKE.VectorRknnSink_Repeat(RknnSink.getCPtr(value), count);
    VectorRknnSink ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorRknnSink(cPtr, true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    FRCVCorePINVOKE.VectorRknnSink_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    FRCVCorePINVOKE.VectorRknnSink_Reverse__SWIG_1(swigCPtr, index, count);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorRknnSink values) {
    FRCVCorePINVOKE.VectorRknnSink_SetRange(swigCPtr, index, VectorRknnSink.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

}
