//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorApriltagSink : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<ApriltagSink>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorApriltagSink(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorApriltagSink obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorApriltagSink obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorApriltagSink() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FRCVCorePINVOKE.delete_VectorApriltagSink(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorApriltagSink(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ApriltagSink element in c) {
      this.Add(element);
    }
  }

  public VectorApriltagSink(global::System.Collections.Generic.IEnumerable<ApriltagSink> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ApriltagSink element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ApriltagSink this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(ApriltagSink[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(ApriltagSink[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, ApriltagSink[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public ApriltagSink[] ToArray() {
    ApriltagSink[] array = new ApriltagSink[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<ApriltagSink> global::System.Collections.Generic.IEnumerable<ApriltagSink>.GetEnumerator() {
    return new VectorApriltagSinkEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorApriltagSinkEnumerator(this);
  }

  public VectorApriltagSinkEnumerator GetEnumerator() {
    return new VectorApriltagSinkEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorApriltagSinkEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<ApriltagSink>
  {
    private VectorApriltagSink collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorApriltagSinkEnumerator(VectorApriltagSink collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ApriltagSink Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (ApriltagSink)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorApriltagSink() : this(FRCVCorePINVOKE.new_VectorApriltagSink__SWIG_0(), true) {
  }

  public VectorApriltagSink(VectorApriltagSink other) : this(FRCVCorePINVOKE.new_VectorApriltagSink__SWIG_1(VectorApriltagSink.getCPtr(other)), true) {
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    FRCVCorePINVOKE.VectorApriltagSink_Clear(swigCPtr);
  }

  public void Add(ApriltagSink x) {
    FRCVCorePINVOKE.VectorApriltagSink_Add(swigCPtr, ApriltagSink.getCPtr(x));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = FRCVCorePINVOKE.VectorApriltagSink_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = FRCVCorePINVOKE.VectorApriltagSink_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = FRCVCorePINVOKE.VectorApriltagSink_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    FRCVCorePINVOKE.VectorApriltagSink_reserve(swigCPtr, n);
  }

  public VectorApriltagSink(int capacity) : this(FRCVCorePINVOKE.new_VectorApriltagSink__SWIG_2(capacity), true) {
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private ApriltagSink getitemcopy(int index) {
    ApriltagSink ret = new ApriltagSink(FRCVCorePINVOKE.VectorApriltagSink_getitemcopy(swigCPtr, index), true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ApriltagSink getitem(int index) {
    ApriltagSink ret = new ApriltagSink(FRCVCorePINVOKE.VectorApriltagSink_getitem(swigCPtr, index), false);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ApriltagSink val) {
    FRCVCorePINVOKE.VectorApriltagSink_setitem(swigCPtr, index, ApriltagSink.getCPtr(val));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorApriltagSink values) {
    FRCVCorePINVOKE.VectorApriltagSink_AddRange(swigCPtr, VectorApriltagSink.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorApriltagSink GetRange(int index, int count) {
    global::System.IntPtr cPtr = FRCVCorePINVOKE.VectorApriltagSink_GetRange(swigCPtr, index, count);
    VectorApriltagSink ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorApriltagSink(cPtr, true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ApriltagSink x) {
    FRCVCorePINVOKE.VectorApriltagSink_Insert(swigCPtr, index, ApriltagSink.getCPtr(x));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorApriltagSink values) {
    FRCVCorePINVOKE.VectorApriltagSink_InsertRange(swigCPtr, index, VectorApriltagSink.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    FRCVCorePINVOKE.VectorApriltagSink_RemoveAt(swigCPtr, index);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    FRCVCorePINVOKE.VectorApriltagSink_RemoveRange(swigCPtr, index, count);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorApriltagSink Repeat(ApriltagSink value, int count) {
    global::System.IntPtr cPtr = FRCVCorePINVOKE.VectorApriltagSink_Repeat(ApriltagSink.getCPtr(value), count);
    VectorApriltagSink ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorApriltagSink(cPtr, true);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    FRCVCorePINVOKE.VectorApriltagSink_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    FRCVCorePINVOKE.VectorApriltagSink_Reverse__SWIG_1(swigCPtr, index, count);
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorApriltagSink values) {
    FRCVCorePINVOKE.VectorApriltagSink_SetRange(swigCPtr, index, VectorApriltagSink.getCPtr(values));
    if (FRCVCorePINVOKE.SWIGPendingException.Pending) throw FRCVCorePINVOKE.SWIGPendingException.Retrieve();
  }

}
