//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Image8U : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Image8U(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Image8U obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Image8U obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Image8U() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libFRCVLibPINVOKE.delete_Image8U(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int width {
    set {
      libFRCVLibPINVOKE.Image8U_width_set(swigCPtr, value);
    } 
    get {
      int ret = libFRCVLibPINVOKE.Image8U_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      libFRCVLibPINVOKE.Image8U_height_set(swigCPtr, value);
    } 
    get {
      int ret = libFRCVLibPINVOKE.Image8U_height_get(swigCPtr);
      return ret;
    } 
  }

  public int stride {
    set {
      libFRCVLibPINVOKE.Image8U_stride_set(swigCPtr, value);
    } 
    get {
      int ret = libFRCVLibPINVOKE.Image8U_stride_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint8_t buf {
    set {
      libFRCVLibPINVOKE.Image8U_buf_set(swigCPtr, SWIGTYPE_p_uint8_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = libFRCVLibPINVOKE.Image8U_buf_get(swigCPtr);
      SWIGTYPE_p_uint8_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
      return ret;
    } 
  }

  public Image8U() : this(libFRCVLibPINVOKE.new_Image8U(), true) {
  }

}
