//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class libFRCVLibPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="SWIGRegisterExceptionCallbacks_libFRCVLib")]
    public static extern void SWIGRegisterExceptionCallbacks_libFRCVLib(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_libFRCVLib")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_libFRCVLib(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_libFRCVLib(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_libFRCVLib(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="SWIGRegisterStringCallback_libFRCVLib")]
    public static extern void SWIGRegisterStringCallback_libFRCVLib(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_libFRCVLib(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  public class SWIGStringWithLengthHelper {

    [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="SWIG_csharp_string_to_c")]
    private static extern global::System.IntPtr SWIG_csharp_string_to_c0(int size, int len, [global::System.Runtime.InteropServices.In,global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr, SizeParamIndex=0)] string str);

    [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="SWIG_csharp_string_size")]
    private static extern int SWIG_csharp_string_size(global::System.IntPtr str);

    [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="SWIG_csharp_string_str")]
    private static extern global::System.IntPtr SWIG_csharp_string_str(global::System.IntPtr str);

    public static global::System.IntPtr SWIG_csharp_string_to_c(string str) {
      if (str == null)
        return global::System.IntPtr.Zero;
      global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
      return SWIG_csharp_string_to_c0(utf8.GetByteCount(str), str.Length, str);
    }

    public static string SWIG_c_to_csharp_string(global::System.IntPtr str) {
      int size = SWIG_csharp_string_size(str);
      if (size > 0) {
        global::System.IntPtr s = SWIG_csharp_string_str(str);
        byte[] b = new byte[size];
        global::System.Runtime.InteropServices.Marshal.Copy(s, b, 0, size);
        global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
        return utf8.GetString(b);
      }
      return null;
    }
  }


  static libFRCVLibPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraHardwareInfo_name_set")]
  public static extern void CameraHardwareInfo_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraHardwareInfo_name_get")]
  public static extern string CameraHardwareInfo_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraHardwareInfo_path_set")]
  public static extern void CameraHardwareInfo_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraHardwareInfo_path_get")]
  public static extern string CameraHardwareInfo_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_CameraHardwareInfo")]
  public static extern global::System.IntPtr new_CameraHardwareInfo();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_CameraHardwareInfo")]
  public static extern void delete_CameraHardwareInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_Manager__SWIG_0")]
  public static extern global::System.IntPtr new_Manager__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_Manager__SWIG_1")]
  public static extern global::System.IntPtr new_Manager__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_Manager")]
  public static extern void delete_Manager(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_getAllSinks")]
  public static extern global::System.IntPtr Manager_getAllSinks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_getAllSources")]
  public static extern global::System.IntPtr Manager_getAllSources(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_enumerateAvailableCameras")]
  public static extern global::System.IntPtr Manager_enumerateAvailableCameras(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_bindSourceToSink")]
  public static extern bool Manager_bindSourceToSink(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_unbindSourceFromSink")]
  public static extern bool Manager_unbindSourceFromSink(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_createCameraSource")]
  public static extern int Manager_createCameraSource(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_createVideoFileSource")]
  public static extern int Manager_createVideoFileSource(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_createImageFileSource")]
  public static extern int Manager_createImageFileSource(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_createApriltagSink")]
  public static extern int Manager_createApriltagSink(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_createObjectDetectionSink")]
  public static extern int Manager_createObjectDetectionSink(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_createRecordingSink")]
  public static extern int Manager_createRecordingSink(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_startAllSources")]
  public static extern void Manager_startAllSources(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_stopAllSources")]
  public static extern void Manager_stopAllSources(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_stopSourceById")]
  public static extern bool Manager_stopSourceById(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_startSourceById")]
  public static extern bool Manager_startSourceById(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_startAllSinks")]
  public static extern void Manager_startAllSinks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_stopAllSinks")]
  public static extern void Manager_stopAllSinks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_startSinkById")]
  public static extern bool Manager_startSinkById(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_stopSinkById")]
  public static extern bool Manager_stopSinkById(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_getAllSinkStatus")]
  public static extern string Manager_getAllSinkStatus(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_getSinkStatusById")]
  public static extern string Manager_getSinkStatusById(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_getSinkResult")]
  public static extern string Manager_getSinkResult(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_getAllSinkResults")]
  public static extern string Manager_getAllSinkResults(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_createCameraCalibrationSink")]
  public static extern int Manager_createCameraCalibrationSink(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_bindSourceToCalibrationSink")]
  public static extern void Manager_bindSourceToCalibrationSink(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_cameraCalibrationSinkGrabFrame")]
  public static extern void Manager_cameraCalibrationSinkGrabFrame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Manager_getCameraCalibrationResults")]
  public static extern global::System.IntPtr Manager_getCameraCalibrationResults(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_fx_set")]
  public static extern void CameraCalibrationResult_fx_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_fx_get")]
  public static extern double CameraCalibrationResult_fx_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_fy_set")]
  public static extern void CameraCalibrationResult_fy_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_fy_get")]
  public static extern double CameraCalibrationResult_fy_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_cx_set")]
  public static extern void CameraCalibrationResult_cx_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_cx_get")]
  public static extern double CameraCalibrationResult_cx_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_cy_set")]
  public static extern void CameraCalibrationResult_cy_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_cy_get")]
  public static extern double CameraCalibrationResult_cy_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_frameSpec_set")]
  public static extern void CameraCalibrationResult_frameSpec_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_CameraCalibrationResult_frameSpec_get")]
  public static extern global::System.IntPtr CameraCalibrationResult_frameSpec_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_CameraCalibrationResult__SWIG_0")]
  public static extern global::System.IntPtr new_CameraCalibrationResult__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_CameraCalibrationResult__SWIG_1")]
  public static extern global::System.IntPtr new_CameraCalibrationResult__SWIG_1(double jarg1, double jarg2, double jarg3, double jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_CameraCalibrationResult")]
  public static extern void delete_CameraCalibrationResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_Log")]
  public static extern global::System.IntPtr new_Log(int jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Log_GetLogLevel")]
  public static extern int Log_GetLogLevel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Log_GetMessage")]
  public static extern string Log_GetMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Log_GetLogLevelString")]
  public static extern string Log_GetLogLevelString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_Log")]
  public static extern void delete_Log(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_Logger__SWIG_0")]
  public static extern global::System.IntPtr new_Logger__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_Logger__SWIG_1")]
  public static extern global::System.IntPtr new_Logger__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_Logger")]
  public static extern void delete_Logger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Logger_enterLog__SWIG_0")]
  public static extern void Logger_enterLog__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Logger_enterLog__SWIG_1")]
  public static extern void Logger_enterLog__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Logger_enterLog__SWIG_2")]
  public static extern void Logger_enterLog__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Logger_clearAllLogs")]
  public static extern void Logger_clearAllLogs(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_Logger_flushLogs")]
  public static extern void Logger_flushLogs(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorInt__SWIG_0")]
  public static extern global::System.IntPtr new_VectorInt__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorInt__SWIG_1")]
  public static extern global::System.IntPtr new_VectorInt__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_Clear")]
  public static extern void VectorInt_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_Add")]
  public static extern void VectorInt_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_size")]
  public static extern uint VectorInt_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_empty")]
  public static extern bool VectorInt_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_capacity")]
  public static extern uint VectorInt_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_reserve")]
  public static extern void VectorInt_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorInt__SWIG_2")]
  public static extern global::System.IntPtr new_VectorInt__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_getitemcopy")]
  public static extern int VectorInt_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_getitem")]
  public static extern int VectorInt_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_setitem")]
  public static extern void VectorInt_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_AddRange")]
  public static extern void VectorInt_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_GetRange")]
  public static extern global::System.IntPtr VectorInt_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_Insert")]
  public static extern void VectorInt_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_InsertRange")]
  public static extern void VectorInt_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_RemoveAt")]
  public static extern void VectorInt_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_RemoveRange")]
  public static extern void VectorInt_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_Repeat")]
  public static extern global::System.IntPtr VectorInt_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_Reverse__SWIG_0")]
  public static extern void VectorInt_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_Reverse__SWIG_1")]
  public static extern void VectorInt_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_SetRange")]
  public static extern void VectorInt_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_Contains")]
  public static extern bool VectorInt_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_IndexOf")]
  public static extern int VectorInt_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_LastIndexOf")]
  public static extern int VectorInt_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorInt_Remove")]
  public static extern bool VectorInt_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_VectorInt")]
  public static extern void delete_VectorInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorString__SWIG_0")]
  public static extern global::System.IntPtr new_VectorString__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorString__SWIG_1")]
  public static extern global::System.IntPtr new_VectorString__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_Clear")]
  public static extern void VectorString_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_Add")]
  public static extern void VectorString_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_size")]
  public static extern uint VectorString_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_empty")]
  public static extern bool VectorString_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_capacity")]
  public static extern uint VectorString_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_reserve")]
  public static extern void VectorString_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorString__SWIG_2")]
  public static extern global::System.IntPtr new_VectorString__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_getitemcopy")]
  public static extern string VectorString_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_getitem")]
  public static extern string VectorString_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_setitem")]
  public static extern void VectorString_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_AddRange")]
  public static extern void VectorString_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_GetRange")]
  public static extern global::System.IntPtr VectorString_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_Insert")]
  public static extern void VectorString_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_InsertRange")]
  public static extern void VectorString_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_RemoveAt")]
  public static extern void VectorString_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_RemoveRange")]
  public static extern void VectorString_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_Repeat")]
  public static extern global::System.IntPtr VectorString_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_Reverse__SWIG_0")]
  public static extern void VectorString_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_Reverse__SWIG_1")]
  public static extern void VectorString_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_SetRange")]
  public static extern void VectorString_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_Contains")]
  public static extern bool VectorString_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_IndexOf")]
  public static extern int VectorString_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_LastIndexOf")]
  public static extern int VectorString_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorString_Remove")]
  public static extern bool VectorString_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_VectorString")]
  public static extern void delete_VectorString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorLog__SWIG_0")]
  public static extern global::System.IntPtr new_VectorLog__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorLog__SWIG_1")]
  public static extern global::System.IntPtr new_VectorLog__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_Clear")]
  public static extern void VectorLog_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_Add")]
  public static extern void VectorLog_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_size")]
  public static extern uint VectorLog_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_empty")]
  public static extern bool VectorLog_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_capacity")]
  public static extern uint VectorLog_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_reserve")]
  public static extern void VectorLog_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorLog__SWIG_2")]
  public static extern global::System.IntPtr new_VectorLog__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_getitemcopy")]
  public static extern global::System.IntPtr VectorLog_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_getitem")]
  public static extern global::System.IntPtr VectorLog_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_setitem")]
  public static extern void VectorLog_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_AddRange")]
  public static extern void VectorLog_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_GetRange")]
  public static extern global::System.IntPtr VectorLog_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_Insert")]
  public static extern void VectorLog_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_InsertRange")]
  public static extern void VectorLog_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_RemoveAt")]
  public static extern void VectorLog_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_RemoveRange")]
  public static extern void VectorLog_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_Repeat")]
  public static extern global::System.IntPtr VectorLog_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_Reverse__SWIG_0")]
  public static extern void VectorLog_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_Reverse__SWIG_1")]
  public static extern void VectorLog_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorLog_SetRange")]
  public static extern void VectorLog_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_VectorLog")]
  public static extern void delete_VectorLog(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorCameraHardwareInfo__SWIG_0")]
  public static extern global::System.IntPtr new_VectorCameraHardwareInfo__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorCameraHardwareInfo__SWIG_1")]
  public static extern global::System.IntPtr new_VectorCameraHardwareInfo__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_Clear")]
  public static extern void VectorCameraHardwareInfo_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_Add")]
  public static extern void VectorCameraHardwareInfo_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_size")]
  public static extern uint VectorCameraHardwareInfo_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_empty")]
  public static extern bool VectorCameraHardwareInfo_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_capacity")]
  public static extern uint VectorCameraHardwareInfo_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_reserve")]
  public static extern void VectorCameraHardwareInfo_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorCameraHardwareInfo__SWIG_2")]
  public static extern global::System.IntPtr new_VectorCameraHardwareInfo__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_getitemcopy")]
  public static extern global::System.IntPtr VectorCameraHardwareInfo_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_getitem")]
  public static extern global::System.IntPtr VectorCameraHardwareInfo_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_setitem")]
  public static extern void VectorCameraHardwareInfo_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_AddRange")]
  public static extern void VectorCameraHardwareInfo_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_GetRange")]
  public static extern global::System.IntPtr VectorCameraHardwareInfo_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_Insert")]
  public static extern void VectorCameraHardwareInfo_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_InsertRange")]
  public static extern void VectorCameraHardwareInfo_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_RemoveAt")]
  public static extern void VectorCameraHardwareInfo_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_RemoveRange")]
  public static extern void VectorCameraHardwareInfo_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_Repeat")]
  public static extern global::System.IntPtr VectorCameraHardwareInfo_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_Reverse__SWIG_0")]
  public static extern void VectorCameraHardwareInfo_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_Reverse__SWIG_1")]
  public static extern void VectorCameraHardwareInfo_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorCameraHardwareInfo_SetRange")]
  public static extern void VectorCameraHardwareInfo_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_VectorCameraHardwareInfo")]
  public static extern void delete_VectorCameraHardwareInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorFrame__SWIG_0")]
  public static extern global::System.IntPtr new_VectorFrame__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorFrame__SWIG_1")]
  public static extern global::System.IntPtr new_VectorFrame__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_Clear")]
  public static extern void VectorFrame_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_Add")]
  public static extern void VectorFrame_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_size")]
  public static extern uint VectorFrame_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_empty")]
  public static extern bool VectorFrame_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_capacity")]
  public static extern uint VectorFrame_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_reserve")]
  public static extern void VectorFrame_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorFrame__SWIG_2")]
  public static extern global::System.IntPtr new_VectorFrame__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_getitemcopy")]
  public static extern global::System.IntPtr VectorFrame_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_getitem")]
  public static extern global::System.IntPtr VectorFrame_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_setitem")]
  public static extern void VectorFrame_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_AddRange")]
  public static extern void VectorFrame_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_GetRange")]
  public static extern global::System.IntPtr VectorFrame_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_Insert")]
  public static extern void VectorFrame_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_InsertRange")]
  public static extern void VectorFrame_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_RemoveAt")]
  public static extern void VectorFrame_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_RemoveRange")]
  public static extern void VectorFrame_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_Repeat")]
  public static extern global::System.IntPtr VectorFrame_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_Reverse__SWIG_0")]
  public static extern void VectorFrame_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_Reverse__SWIG_1")]
  public static extern void VectorFrame_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrame_SetRange")]
  public static extern void VectorFrame_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_VectorFrame")]
  public static extern void delete_VectorFrame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorFrameSpec__SWIG_0")]
  public static extern global::System.IntPtr new_VectorFrameSpec__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorFrameSpec__SWIG_1")]
  public static extern global::System.IntPtr new_VectorFrameSpec__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_Clear")]
  public static extern void VectorFrameSpec_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_Add")]
  public static extern void VectorFrameSpec_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_size")]
  public static extern uint VectorFrameSpec_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_empty")]
  public static extern bool VectorFrameSpec_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_capacity")]
  public static extern uint VectorFrameSpec_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_reserve")]
  public static extern void VectorFrameSpec_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_VectorFrameSpec__SWIG_2")]
  public static extern global::System.IntPtr new_VectorFrameSpec__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_getitemcopy")]
  public static extern global::System.IntPtr VectorFrameSpec_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_getitem")]
  public static extern global::System.IntPtr VectorFrameSpec_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_setitem")]
  public static extern void VectorFrameSpec_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_AddRange")]
  public static extern void VectorFrameSpec_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_GetRange")]
  public static extern global::System.IntPtr VectorFrameSpec_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_Insert")]
  public static extern void VectorFrameSpec_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_InsertRange")]
  public static extern void VectorFrameSpec_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_RemoveAt")]
  public static extern void VectorFrameSpec_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_RemoveRange")]
  public static extern void VectorFrameSpec_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_Repeat")]
  public static extern global::System.IntPtr VectorFrameSpec_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_Reverse__SWIG_0")]
  public static extern void VectorFrameSpec_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_Reverse__SWIG_1")]
  public static extern void VectorFrameSpec_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_VectorFrameSpec_SetRange")]
  public static extern void VectorFrameSpec_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_VectorFrameSpec")]
  public static extern void delete_VectorFrameSpec(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_UniquePtrLog")]
  public static extern global::System.IntPtr new_UniquePtrLog();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_UniquePtrLog")]
  public static extern void delete_UniquePtrLog(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_new_UniquePtrFrame")]
  public static extern global::System.IntPtr new_UniquePtrFrame();

  [global::System.Runtime.InteropServices.DllImport("libFRCVLib", EntryPoint="CSharp_delete_UniquePtrFrame")]
  public static extern void delete_UniquePtrFrame(global::System.Runtime.InteropServices.HandleRef jarg1);
}
