//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorFrameSpec : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<SWIGTYPE_p_FrameSpec>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorFrameSpec(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorFrameSpec obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorFrameSpec obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorFrameSpec() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FRCVLibPINVOKE.delete_VectorFrameSpec(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorFrameSpec(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (SWIGTYPE_p_FrameSpec element in c) {
      this.Add(element);
    }
  }

  public VectorFrameSpec(global::System.Collections.Generic.IEnumerable<SWIGTYPE_p_FrameSpec> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (SWIGTYPE_p_FrameSpec element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public SWIGTYPE_p_FrameSpec this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(SWIGTYPE_p_FrameSpec[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(SWIGTYPE_p_FrameSpec[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, SWIGTYPE_p_FrameSpec[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public SWIGTYPE_p_FrameSpec[] ToArray() {
    SWIGTYPE_p_FrameSpec[] array = new SWIGTYPE_p_FrameSpec[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<SWIGTYPE_p_FrameSpec> global::System.Collections.Generic.IEnumerable<SWIGTYPE_p_FrameSpec>.GetEnumerator() {
    return new VectorFrameSpecEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorFrameSpecEnumerator(this);
  }

  public VectorFrameSpecEnumerator GetEnumerator() {
    return new VectorFrameSpecEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorFrameSpecEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<SWIGTYPE_p_FrameSpec>
  {
    private VectorFrameSpec collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorFrameSpecEnumerator(VectorFrameSpec collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public SWIGTYPE_p_FrameSpec Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (SWIGTYPE_p_FrameSpec)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorFrameSpec() : this(FRCVLibPINVOKE.new_VectorFrameSpec__SWIG_0(), true) {
  }

  public VectorFrameSpec(VectorFrameSpec other) : this(FRCVLibPINVOKE.new_VectorFrameSpec__SWIG_1(VectorFrameSpec.getCPtr(other)), true) {
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    FRCVLibPINVOKE.VectorFrameSpec_Clear(swigCPtr);
  }

  public void Add(SWIGTYPE_p_FrameSpec x) {
    FRCVLibPINVOKE.VectorFrameSpec_Add(swigCPtr, SWIGTYPE_p_FrameSpec.getCPtr(x));
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = FRCVLibPINVOKE.VectorFrameSpec_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = FRCVLibPINVOKE.VectorFrameSpec_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = FRCVLibPINVOKE.VectorFrameSpec_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    FRCVLibPINVOKE.VectorFrameSpec_reserve(swigCPtr, n);
  }

  public VectorFrameSpec(int capacity) : this(FRCVLibPINVOKE.new_VectorFrameSpec__SWIG_2(capacity), true) {
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  private SWIGTYPE_p_FrameSpec getitemcopy(int index) {
    SWIGTYPE_p_FrameSpec ret = new SWIGTYPE_p_FrameSpec(FRCVLibPINVOKE.VectorFrameSpec_getitemcopy(swigCPtr, index), true);
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private SWIGTYPE_p_FrameSpec getitem(int index) {
    SWIGTYPE_p_FrameSpec ret = new SWIGTYPE_p_FrameSpec(FRCVLibPINVOKE.VectorFrameSpec_getitem(swigCPtr, index), false);
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, SWIGTYPE_p_FrameSpec val) {
    FRCVLibPINVOKE.VectorFrameSpec_setitem(swigCPtr, index, SWIGTYPE_p_FrameSpec.getCPtr(val));
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorFrameSpec values) {
    FRCVLibPINVOKE.VectorFrameSpec_AddRange(swigCPtr, VectorFrameSpec.getCPtr(values));
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorFrameSpec GetRange(int index, int count) {
    global::System.IntPtr cPtr = FRCVLibPINVOKE.VectorFrameSpec_GetRange(swigCPtr, index, count);
    VectorFrameSpec ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorFrameSpec(cPtr, true);
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, SWIGTYPE_p_FrameSpec x) {
    FRCVLibPINVOKE.VectorFrameSpec_Insert(swigCPtr, index, SWIGTYPE_p_FrameSpec.getCPtr(x));
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorFrameSpec values) {
    FRCVLibPINVOKE.VectorFrameSpec_InsertRange(swigCPtr, index, VectorFrameSpec.getCPtr(values));
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    FRCVLibPINVOKE.VectorFrameSpec_RemoveAt(swigCPtr, index);
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    FRCVLibPINVOKE.VectorFrameSpec_RemoveRange(swigCPtr, index, count);
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorFrameSpec Repeat(SWIGTYPE_p_FrameSpec value, int count) {
    global::System.IntPtr cPtr = FRCVLibPINVOKE.VectorFrameSpec_Repeat(SWIGTYPE_p_FrameSpec.getCPtr(value), count);
    VectorFrameSpec ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorFrameSpec(cPtr, true);
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    FRCVLibPINVOKE.VectorFrameSpec_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    FRCVLibPINVOKE.VectorFrameSpec_Reverse__SWIG_1(swigCPtr, index, count);
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorFrameSpec values) {
    FRCVLibPINVOKE.VectorFrameSpec_SetRange(swigCPtr, index, VectorFrameSpec.getCPtr(values));
    if (FRCVLibPINVOKE.SWIGPendingException.Pending) throw FRCVLibPINVOKE.SWIGPendingException.Retrieve();
  }

}
